- config.toml
- static/CNAME
Mailchimp sign up form is broken for this project - removed.
> Mailchimp sign up form removed 

- config.toml
- layouts/index.html
- layouts/partials/groups-io.html
- layouts/partials/mailchimp-signup.html
I have tested this locally. Everything appears to be working normally. There is additional work being done to make the site look better.
> Added groups.io signup form

- config.toml
This adds the v0.2 announcement, but leaves the question of a blog outstanding. I've logged #6 to address that decision.
Signed-off-by: Dan Barker <barkerd427@gmail.com>
> Added v0.2 Announcement

- config.toml
May has not occurred this year. Do we mean May 2018?
> Clarify "May" date

- config.toml
> remove Today

- config.toml
> Announce v0.3

- config.toml
> v1.0 announce

- assets/sass/style.sass
- config.toml
- content/blog/_index.md
- content/blog/example-post.md
- layouts/blog/list.html
- layouts/blog/single.html
- layouts/partials/blog/content.html
- layouts/partials/blog/hero.html
- layouts/partials/blog/posts.html
- layouts/partials/blog/sidebar.html
- layouts/partials/navbar.html
Fixes #6
Landing page: https://deploy-preview-19--cloudevents-io.netlify.com/blog/
Example post: https://deploy-preview-19--cloudevents-io.netlify.com/blog/example-post
**NOTE**: The example will not show up on the production site, as it's marked as a [draft](https://gohugo.io/getting-started/usage/#draft-future-and-expired-content), and the link to the blog in the navbar won't show up until the first real post is published.
> Add blog template

- config.toml
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>
> Fixing Technical Oversight Committee link

- data/integrations.yaml
> fix bad href

- config.toml
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>
deliverying -> delivering
> Small typo fix

- config.toml
- fix link to a governance model
- add link to time zone translator as I had to manually check that 
- add link to meeting notes as I've spent at least 15min trying to find it
> update links on home page

- config.toml
Hi there, I noticed a broken link. This fixes it.
> Fix broken Governance link

- config.toml
- layouts/partials/home/release.html
> announce v1.0.1

- config.toml
> fix link to minutes

- config.toml
Added Rust and PowerShell into respective sections.
Closes: #54
Signed-off-by: Michael Gasch <mgasch@vmware.com>
> Update list of SDKs

- config.toml
I'm not sure if you want to link it to a specific branch?
> fix link to specification

- config.toml
Signed-off-by: Drew Nguyen <29507308+drunewin@users.noreply.github.com>
> fix: update project links

- config.toml
- layouts/partials/home/release.html
Fixes #64 
Signed-off-by: Doug Davis <dug@microsoft.com>
> add v1.0.2 release info

- data/en/integrations.yaml
The product mentioned in the description is no longer available. Including link to blog post that highlights how different SAP products have embraced the Cloud Events specification
> Updated description for SAP
